FROM alpine:latest

RUN mkdir /app

WORKDIR /app

ARG TARGETARCH
COPY binaries/server-linux-${TARGETARCH} ./server
COPY binaries/admin-linux-${TARGETARCH} ./admin
COPY binaries/migrate-linux-${TARGETARCH} ./migrate
COPY start.sh ./start.sh

RUN chmod +x ./server ./admin ./migrate ./start.sh

# Copy migration files
COPY migrations ./migrations

ENTRYPOINT ["./start.sh"]
