name: Build and Push Docker Image (On Release)

on:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          check-latest: true

      - name: Download Dependencies
        run: make deps

      - name: Build binaries for all architectures
        run: |
          mkdir -p binaries
          # Build for amd64
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 make build
          mv otp-server-linux-amd64 binaries/
          
          # Build for arm64
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 make build
          mv otp-server-linux-arm64 binaries/

      - name: Build migration binaries
        run: |
          # Get migrate module and build binaries
          go get github.com/golang-migrate/migrate/v4/cmd/migrate

          # Build migrate binary for amd64
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags 'postgres' -o binaries/migrate-linux-amd64 github.com/golang-migrate/migrate/v4/cmd/migrate

          # Build migrate binary for arm64
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -tags 'postgres' -o binaries/migrate-linux-arm64 github.com/golang-migrate/migrate/v4/cmd/migrate

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/mosed3/otp-server

      - name: Set Docker tags
        id: tags
        run: |
          if [ "${{ github.event.release.prerelease }}" = "true" ]; then
            # Pre-release: only version tags
            echo "DOCKER_TAGS=ghcr.io/mosed3/otp-server:${{ github.ref_name }}" >> $GITHUB_ENV
          else
            # Regular release: version tags + latest tags
            echo "DOCKER_TAGS=ghcr.io/mosed3/otp-server:${{ github.ref_name }},ghcr.io/mosed3/otp-server:latest" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.multi
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
